# Generated by Django 3.0.5 on 2020-06-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='Shipping',
        ),
    ]
